homeassistant:
  name: SMARTBOX
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml

# Enable this for production
http:
  # server_port: 80
  # api_password: !secret http_api_password
  # ssl_certificate: !secret http_ssl_certificate
  # ssl_key: !secret http_ssl_key
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io



############################
# Zones                    #
############################

# https://home-assistant.io/components/zone/

zone:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 1000
  icon: mdi:briefcase



############################
# Components               #
############################

# automation: !include automation.yaml
camera: !include camera.yaml
group: !include group.yaml
# input_select: !include input_select.yaml
# input_slider: !include input_slider.yaml
# notify: !include notify.yaml
script: !include script.yaml
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
sun: # Track the sun
switch: !include switch.yaml



############################
# Enables                  #
############################

conversation:   # Allows you to issue voice commands from the frontend in enabled browsers
# discovery:    # Discover some devices automatically
frontend:       # Enables the frontend
history:        # Enables support for tracking state changes over time.
# introduction: # Show links to resources in log and frontend
logbook:        # View all events in a logbook
# updater:      # Checks for available updates
